# Generated by Django 5.2.4 on 2025-07-04 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('sujet', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('A_VENIR', 'À venir'), ('PASSEE', 'Passée'), ('ANNULEE', 'Annulée')], default='A_VENIR', max_length=10)),
                ('notes_coach', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_client', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_coach', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coach', 'date', 'heure_debut')},
            },
        ),
    ]
