# Generated by Django 5.2.4 on 2025-07-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_alter_seance_sujet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='statut',
        ),
        migrations.AlterField(
            model_name='seance',
            name='sujet',
            field=models.CharField(choices=[('PERTE POIDS', '🔥 Perte de poids / sèche'), ('PRISE MASSE', '💪 Prise de masse / hypertrophie'), ('SOUPLESSE', '🧘 Souplesse et mobilité'), ('REMISE FORME', '🏃 Remise en forme / reprise du sport'), ('RENFORCEMENT', '🧍\u200d♂️ Renforcement musculaire général'), ('PREPA PHYSIQUE', '⚽ Préparation physique spécifique (sport en particulier)'), ('EQUILIBRE', '♻️ Équilibre sport / récupération / sommeil'), ('TRAVAIL CIBLE', '🦵 Travail ciblé (abdos, fessiers, bras, jambes…)'), ('MOTIVATION', "🧠 Motivation et discipline dans l'entraînement"), ('POST BLESSURE', '👩\u200d⚕️ Accompagnement post-blessure / réathlétisation'), ('ENDURANCE', '⏱️ Coaching pour améliorer l’endurance / cardio'), ('PROGRAMME', '📅 Création de programme personnalisé'), ('AUTRE', '❓ Autre (à préciser)')], max_length=100),
        ),
    ]
